# Generated by Django 4.0.4 on 2022-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереї',
                'db_table': 'gallery',
                'managed': False,
            },
        ),
    ]
