# Generated by Django 4.0.4 on 2022-05-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'managed': False, 'verbose_name': 'Тип номеру', 'verbose_name_plural': 'Типи номерів'},
        ),
    ]
