# Generated by Django 4.0.4 on 2022-05-20 05:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Останній вхід')),
                ('is_superuser', models.BooleanField(verbose_name='Суперюзер')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name="Ім'я користувача")),
                ('first_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=150, verbose_name='Призвище')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Email адреса')),
                ('is_staff', models.BooleanField(verbose_name='Персонал')),
                ('is_active', models.BooleanField(verbose_name='Активний')),
                ('date_joined', models.DateTimeField(verbose_name='Дата приєднання')),
            ],
            options={
                'verbose_name': 'Аутентифікований користувач',
                'verbose_name_plural': 'Аутентифіковані користувачі',
                'db_table': 'auth_user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Номер телефону',
                'verbose_name_plural': 'Номери телефонів',
                'db_table': 'phone',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Зміст')),
                ('timestamp_review', models.DateTimeField(auto_now_add=True, verbose_name='Позначка часу')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'db_table': 'reviews',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_title', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Назва типу кімнати')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип номеру',
                'verbose_name_plural': 'Типи номерів',
                'db_table': 'room_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
    ]
