# Generated by Django 4.0.4 on 2022-05-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Зміст')),
                ('timestamp_review', models.DateTimeField(auto_now_add=True, verbose_name='Позначка часу')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'db_table': 'reviews',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
