# Generated by Django 4.0.4 on 2022-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Номер телефону',
                'verbose_name_plural': 'Номери телефонів',
                'db_table': 'phone',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'verbose_name': 'Аутентифікований користувач', 'verbose_name_plural': 'Аутентифіковані користувачі'},
        ),
    ]
