# Generated by Django 4.0.4 on 2022-05-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_roomtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
